"""added is_deleted

Revision ID: 6acbf669f3a5
Revises: 7fe0bd0c0280
Create Date: 2025-06-15 18:03:10.258206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acbf669f3a5'
down_revision: Union[str, None] = '7fe0bd0c0280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_deleted')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    # ### end Alembic commands ###
