"""Add ondelete CASCADE to order_items.product_id

Revision ID: e6c9fb616fe9
Revises: 0d5bcae4f81d
Create Date: 2025-06-13 17:35:08.819149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6c9fb616fe9'
down_revision: Union[str, None] = '0d5bcae4f81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'order_items_product_id_fkey',
        'order_items', 'products',
        ['product_id'], ['id']
        )    # ### end Alembic commands ###
